name: tummoc-app-server

on:
  push:
    branches:
      - master

permissions:
  id-token: write   # Required for OIDC
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS --password-stdin 486408064722.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=tummoc-app
          TAG=${GITHUB_SHA}
          docker build -t $IMAGE_NAME:$TAG -f docker/Dockerfile .
          docker tag $IMAGE_NAME:$TAG 486408064722.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME:$TAG
          docker tag $IMAGE_NAME:$TAG 486408064722.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME:latest
          docker push 486408064722.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME:$TAG
          docker push 486408064722.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME:latest

      - name: Terraform apply
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
