name: CI-CD

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: tummoc-app
  ECR_REGISTRY: 486408064722.dkr.ecr.us-east-1.amazonaws.com

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Verify AWS Login
      run: aws sts get-caller-identity

    #################################################
    # Terraform Setup
    #################################################

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve

    #################################################
    # Build Docker Image
    #################################################

    - name: Set Image Tag
      run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION | \
        docker login --username AWS \
        --password-stdin $ECR_REGISTRY

    - name: Build Docker Image
      run: |
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG -f docker/Dockerfile .

    - name: Tag Image
      run: |
        docker tag $ECR_REPOSITORY:$IMAGE_TAG \
        $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Push Image
      run: |
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    #################################################
    # Deploy to EC2
    #################################################

    - name: Deploy via SSM
      run: |
        aws ssm send-command \
        --targets "Key=tag:App,Values=tummoc-app" \
        --document-name "AWS-RunShellScript" \
        --parameters 'commands=["/home/ec2-user/deploy.sh '${IMAGE_TAG}'"]' \
        --region $AWS_REGION
